# Whether this GitHub repo is engineering related
engineering_project: true
# Name of the repository/project in English
english_name: Image Crawler
# All technologies used
technologies: Python, asyncio
# Whether this repository should be featured on the CC Open Source site
featured: false
